
import numpy as np
import pandas as pd
from pandas.io import sql
import sqlalchemy as sa
import yaml as yml
import json
import demjson
get_ipython().magic(u'matplotlib inline')
pd.set_option('display.max_columns', None)

In [8]:
pd.set_option('display.max_columns', None)

In [9]:
#use RHC port forward
engine = sa.create_engine('mysql://adminx3XudpJ:8amBCz5Xb-a4@127.0.0.1:3306/personality')

In [10]:
con = engine.raw_connection()

In [11]:
df = sql.read_frame("SELECT * FROM BFASopg union select * from bffopg ", con)
df = df.convert_objects(convert_numeric=True)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: read_frame is deprecated, use read_sql
  if __name__ == '__main__':
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app

In [12]:
df.head()

,uniqueid,assignmentid,workerid,hitid,ipaddress,browser,platform,language,cond,counterbalance,codeversion,beginhit,beginexp,endhit,bonus,status,datastring
0,A06844383SJTPQU97CMSO:3F6KKYWMNB2T3GR7DLGSJEWF...,3F6KKYWMNB2T3GR7DLGSJEWF3HSDNF,A06844383SJTPQU97CMSO,3AA88CN98P4T7131M26OFNUTG1DYKP,127.13.130.129,firefox,windows,UNKNOWN,0,0,1,2014-10-23 19:14:20,2014-10-23 19:14:51,2014-10-23 19:21:12,0,4,"{""condition"":0,""counterbalance"":0,""assignmentI..."
1,A10IJLXWZZTN6L:3VW6495TLJ1QDQQCGJCHDF4NPP2YYY,3VW6495TLJ1QDQQCGJCHDF4NPP2YYY,A10IJLXWZZTN6L,3AA88CN98P4T7131M26OFNUTG1DYKP,127.13.130.129,chrome,windows,UNKNOWN,0,0,1,2014-10-23 19:09:11,2014-10-23 19:10:40,2014-10-23 19:28:20,0,4,"{""condition"":0,""counterbalance"":0,""assignmentI..."
2,A1102MP1CZI32V:3NQL1CS15R999WV7B8PX6G0T780VYM,3NQL1CS15R999WV7B8PX6G0T780VYM,A1102MP1CZI32V,3AA88CN98P4T7131M26OFNUTG1DYKP,127.13.130.129,firefox,windows,UNKNOWN,0,0,1,2014-10-23 19:25:16,2014-10-23 19:25:33,2014-10-23 19:35:12,0,4,"{""condition"":0,""counterbalance"":0,""assignmentI..."
3,A1153ZIEQX0ZJ8:3WQ3B2KGE8HXACMYU2RORHVCXVC1BP,3WQ3B2KGE8HXACMYU2RORHVCXVC1BP,A1153ZIEQX0ZJ8,3AA88CN98P4T7131M26OFNUTG1DYKP,127.13.130.129,chrome,windows,UNKNOWN,0,0,1,2014-10-23 19:06:16,2014-10-23 19:06:23,2014-10-23 19:12:06,0,4,"{""condition"":0,""counterbalance"":0,""assignmentI..."
4,A11ZAAI7X8HSM0:3WYGZ5XF3WGYXZPMDYJ1ML1BAPWSKI,3WYGZ5XF3WGYXZPMDYJ1ML1BAPWSKI,A11ZAAI7X8HSM0,3AA88CN98P4T7131M26OFNUTG1DYKP,127.13.130.129,chrome,windows,UNKNOWN,0,0,1,2014-10-23 19:05:36,2014-10-23 19:08:05,2014-10-23 19:27:27,0,4,"{""condition"":0,""counterbalance"":0,""assignmentI..."

In [13]:
len(df)

856

In [14]:
def takestring(row):
    #print json.loads(row['datastring'])
    try:
        d = json.loads(row['datastring'])
    except:
        print row
    else:
   # print jj
        j= d['data']
        for a in j:
            b = a['trialdata']
            if 'answer' in b:
                item_id = b['id']
                rawanswer = b['answer']
                row[item_id] = rawanswer
    #print row
        return pd.Series(row)

In [15]:
df=df[df['status']==4]
df = df.apply(takestring,axis=1)
df = df.convert_objects(convert_numeric=True)

uniqueid          A1MQ9M8OX7BI0X:3SBEHTYCWN44NQB7C1QERRAZZ64IYC
assignmentid                     3SBEHTYCWN44NQB7C1QERRAZZ64IYC
workerid                                         A1MQ9M8OX7BI0X
hitid                            3AA88CN98P4T7131M26OFNUTG1DYKP
ipaddress                                        127.13.130.129
browser                                                  chrome
platform                                                windows
language                                                UNKNOWN
cond                                                          0
counterbalance                                                0
codeversion                                                   1
beginhit                                    2014-10-23 19:11:06
beginexp                                    2014-10-23 19:12:20
endhit                                      2014-10-23 19:40:01
bonus                                                         0
status                                                        4
datastring
Name: 44, dtype: object

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  app.launch_new_instance()

In [35]:
masterdf = df[df['status']==4]

In [50]:
opg_cols = [u'PBR_1+',
 u'PBR_2-',
 u'PBR_3+',
 u'PBR_4+',
 u'PBR_5+',
 u'PBR_6-',
 u'PBR_7-',
 u'PBR_8-',
  u'OPG_9+',
 u'OPG_10+',
 u'OPG_11-',
 u'OPG_12+',
 u'OPG_13+',
 u'OPG_14+',
 u'OPG_15+',
 u'OPG_16+',
 u'OPG_17-',
 u'OPG_18-',
 u'IE_19+',
 u'IE_20+',
 u'IE_21+',
 u'IE_22-',
 u'IE_23-',
 u'IE_24+',
 u'IE_25-',
 u'IE_26-']


# In[12]:

opg = masterdf[opg_cols]

In [51]:
opg.head()

,PBR_1+,PBR_2-,PBR_3+,PBR_4+,PBR_5+,PBR_6-,PBR_7-,PBR_8-,OPG_9+,OPG_10+,OPG_11-,OPG_12+,OPG_13+,OPG_14+,OPG_15+,OPG_16+,OPG_17-,OPG_18-,IE_19+,IE_20+,IE_21+,IE_22-,IE_23-,IE_24+,IE_25-,IE_26-
0,90.03,9.97,90.14,89.81,65.09,9.86,9.97,19.10,90.92,90.48,89.25,89.92,90.48,89.81,89.81,8.74,10.30,89.70,90.26,89.92,50.56,89.59,9.74,89.70,9.35,0.00
1,89.98,10.13,90.42,100.00,89.76,30.62,23.83,19.93,19.82,90.20,24.72,89.87,33.96,35.52,90.87,59.91,10.02,100.00,99.89,90.31,49.89,10.36,89.98,9.02,30.18,0.00
2,69.82,32.41,68.21,64.25,62.81,33.74,37.42,29.84,41.09,62.69,28.40,55.35,32.85,42.43,36.75,50.00,34.74,79.40,38.31,68.26,50.00,73.50,80.73,29.84,35.30,30.85
3,99.33,50.00,95.27,95.04,99.83,20.32,67.48,1.50,75.11,70.10,16.54,49.89,38.70,61.30,54.84,50.00,26.67,70.99,49.94,95.38,50.00,50.00,10.08,38.70,50.00,57.96
4,89.58,7.63,89.58,91.37,90.14,79.85,9.79,10.63,50.00,88.15,73.78,90.32,12.08,74.09,89.70,90.02,49.28,52.17,37.69,70.77,91.04,91.65,9.63,75.89,10.71,7.96

In [42]:
len(opg)

767

In [43]:
sum(opg.duplicated())

0

In [55]:
100 - 2*abs(8.74-50)

17.480000000000004

In [56]:
#Specific Item ADjustments
#Middle Distance
opg['OPG_16+'] = 100-2*abs(opg['OPG_16+']-50)
opg['IE_21+'] = 100-2*abs(opg['IE_21+']-50)

#Stretching, because marking '100%' would mean a '90' without this:
opg['PBR_1+'] = ((opg['PBR_1+']-50)*1.1)+50
opg['PBR_3+'] = ((opg['PBR_3+']-50)*1.1)+50
opg['OPG_15+'] = ((opg['OPG_15+']-50)*1.1)+50

#rounding to within actual limits:
opg['PBR_1+'] = opg['PBR_1+'].apply(lambda x: 100 if x>100 else x)
opg['PBR_3+'] = opg['PBR_3+'].apply(lambda x: 100 if x>100 else x)
opg['OPG_15+'] = opg['OPG_15+'].apply(lambda x: 100 if x>100 else x)
opg['PBR_1+'] = opg['PBR_1+'].apply(lambda x: 0 if x<0 else x)
opg['PBR_3+'] = opg['PBR_3+'].apply(lambda x: 0 if x<0 else x)
opg['OPG_15+'] = opg['OPG_15+'].apply(lambda x: 0 if x<0 else x)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [57]:
opg.head()

,PBR_1+,PBR_2-,PBR_3+,PBR_4+,PBR_5+,PBR_6-,PBR_7-,PBR_8-,OPG_9+,OPG_10+,OPG_11-,OPG_12+,OPG_13+,OPG_14+,OPG_15+,OPG_16+,OPG_17-,OPG_18-,IE_19+,IE_20+,IE_21+,IE_22-,IE_23-,IE_24+,IE_25-,IE_26-
0,94.033,9.97,94.154,89.81,65.09,9.86,9.97,19.10,90.92,90.48,89.25,89.92,90.48,89.81,93.791,17.48,10.30,89.70,90.26,89.92,98.88,89.59,9.74,89.70,9.35,0.00
1,93.978,10.13,94.462,100.00,89.76,30.62,23.83,19.93,19.82,90.20,24.72,89.87,33.96,35.52,94.957,80.18,10.02,100.00,99.89,90.31,99.78,10.36,89.98,9.02,30.18,0.00
2,71.802,32.41,70.031,64.25,62.81,33.74,37.42,29.84,41.09,62.69,28.40,55.35,32.85,42.43,35.425,100.00,34.74,79.40,38.31,68.26,100.00,73.50,80.73,29.84,35.30,30.85
3,100.000,50.00,99.797,95.04,99.83,20.32,67.48,1.50,75.11,70.10,16.54,49.89,38.70,61.30,55.324,100.00,26.67,70.99,49.94,95.38,100.00,50.00,10.08,38.70,50.00,57.96
4,93.538,7.63,93.538,91.37,90.14,79.85,9.79,10.63,50.00,88.15,73.78,90.32,12.08,74.09,93.670,19.96,49.28,52.17,37.69,70.77,17.92,91.65,9.63,75.89,10.71,7.96

In [58]:
for label in opg:
        if label[-1]=='-':
            opg[label]=100-opg[label]
        elif label[-1]=='+':
            pass

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [59]:
opg.head()

,PBR_1+,PBR_2-,PBR_3+,PBR_4+,PBR_5+,PBR_6-,PBR_7-,PBR_8-,OPG_9+,OPG_10+,OPG_11-,OPG_12+,OPG_13+,OPG_14+,OPG_15+,OPG_16+,OPG_17-,OPG_18-,IE_19+,IE_20+,IE_21+,IE_22-,IE_23-,IE_24+,IE_25-,IE_26-
0,94.033,90.03,94.154,89.81,65.09,90.14,90.03,80.90,90.92,90.48,10.75,89.92,90.48,89.81,93.791,17.48,89.70,10.30,90.26,89.92,98.88,10.41,90.26,89.70,90.65,100.00
1,93.978,89.87,94.462,100.00,89.76,69.38,76.17,80.07,19.82,90.20,75.28,89.87,33.96,35.52,94.957,80.18,89.98,0.00,99.89,90.31,99.78,89.64,10.02,9.02,69.82,100.00
2,71.802,67.59,70.031,64.25,62.81,66.26,62.58,70.16,41.09,62.69,71.60,55.35,32.85,42.43,35.425,100.00,65.26,20.60,38.31,68.26,100.00,26.50,19.27,29.84,64.70,69.15
3,100.000,50.00,99.797,95.04,99.83,79.68,32.52,98.50,75.11,70.10,83.46,49.89,38.70,61.30,55.324,100.00,73.33,29.01,49.94,95.38,100.00,50.00,89.92,38.70,50.00,42.04
4,93.538,92.37,93.538,91.37,90.14,20.15,90.21,89.37,50.00,88.15,26.22,90.32,12.08,74.09,93.670,19.96,50.72,47.83,37.69,70.77,17.92,8.35,90.37,75.89,89.29,92.04

In [60]:
opg.to_csv("processed_combined_opg_STUDY_I.csv",index=False)